/**
 * Downloads the webfonts we use from Google Fonts into `static/fonts/`, and
 * generates the `@font-face` CSS that points at those local copies.
 *
 * Run manually (`deno task fonts`) whenever the set of fonts changes; the
 * output is committed, so nothing fetches anything at build or request time.
 *
 *     deno task fonts
 */

import { ensureDir } from '@std/fs'

/**
 * The families and styles we use. Mirrors the classes in
 * `static/css/fonts.css`.
 */
const GOOGLE_FONTS_URL =
  'https://fonts.googleapis.com/css2?family=Courier+Prime:ital,wght@0,400;0,700;1,400;1,700&family=IM+Fell+DW+Pica+SC&family=IM+Fell+DW+Pica:ital@0;1&family=IM+Fell+Double+Pica+SC&family=IM+Fell+Double+Pica:ital@0;1&family=IM+Fell+English+SC&family=IM+Fell+English:ital@0;1&family=IM+Fell+French+Canon+SC&family=IM+Fell+French+Canon:ital@0;1&family=IM+Fell+Great+Primer+SC&family=IM+Fell+Great+Primer:ital@0;1&display=block'

/**
 * Google serves woff2 only to browsers it recognizes; with a non-browser
 * user-agent it falls back to ttf, which is roughly twice the size.
 */
const BROWSER_USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

const FONTS_DIR = './static/fonts'
const GENERATED_CSS = './static/css/_generated-fonts.css'

/** URL path the fonts are served from; `static/` is the server root. */
const FONTS_URL_PATH = '/fonts'

/**
 * The `latin` subset's range always starts here, and every other subset's
 * starts somewhere else, which is enough to tell them apart. We only ship
 * `latin`: every non-ASCII character in the site's content is inside it, and
 * the emoji that aren't fall back to system fonts regardless.
 */
const LATIN_RANGE_PREFIX = 'U+0000-00FF'

type FontFace = {
  family: string
  style: string
  weight: string
  unicodeRange: string
  url: string
}

/** Pull the `@font-face` blocks we care about out of Google's stylesheet. */
const parseFontFaces = (css: string): FontFace[] =>
  [...css.matchAll(/@font-face\s*\{([^}]*)\}/g)]
    .map((match) => match[1] ?? '')
    .map((block) => ({
      family: block.match(/font-family:\s*'([^']+)'/)?.[1] ?? '',
      style: block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal',
      weight: block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400',
      unicodeRange: block.match(/unicode-range:\s*([^;]+)/)?.[1]?.trim() ?? '',
      url: block.match(/url\(([^)]+)\)/)?.[1] ?? '',
    }))
    .filter((face) => face.family && face.url)

/** eg. `IM Fell DW Pica SC` + italic + 700 -> `im-fell-dw-pica-sc-italic-700` */
const fileNameFor = ({ family, style, weight }: FontFace) =>
  [
    family.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-'),
    style === 'italic' ? 'italic' : 'regular',
    weight === '400' ? undefined : weight,
  ]
    .filter((segment) => segment != null)
    .join('-') + '.woff2'

const fontFaceRule = (face: FontFace, fileName: string) =>
  `@font-face {
    font-family: '${face.family}';
    font-style: ${face.style};
    font-weight: ${face.weight};
    font-display: block;
    src: url(${FONTS_URL_PATH}/${fileName}) format('woff2');
}`

const css = await fetch(GOOGLE_FONTS_URL, {
  headers: { 'User-Agent': BROWSER_USER_AGENT },
}).then((res) => res.text())

if (!css.includes('woff2')) {
  throw Error(
    'Google returned a stylesheet without woff2 URLs; the user-agent above is probably no longer recognized as a browser',
  )
}

const allFaces = parseFontFaces(css)
const faces = allFaces.filter((face) =>
  face.unicodeRange.startsWith(LATIN_RANGE_PREFIX)
)

if (faces.length === 0) {
  throw Error(
    'No latin-subset font faces found; has the stylesheet format changed?',
  )
}

await ensureDir(FONTS_DIR)

const downloads = await Promise.all(
  faces.map(async (face) => {
    const fileName = fileNameFor(face)
    const response = await fetch(face.url)
    const bytes = new Uint8Array(await response.arrayBuffer())

    await Deno.writeFile(`${FONTS_DIR}/${fileName}`, bytes)

    return { face, fileName, size: bytes.byteLength }
  }),
)

await Deno.writeTextFile(
  GENERATED_CSS,
  [
    '/* GENERATED by scripts/fetch-fonts.ts - do not edit by hand */',
    ...downloads.map(({ face, fileName }) => fontFaceRule(face, fileName)),
  ].join('\n\n') + '\n',
)

const totalBytes = downloads.reduce((total, { size }) => total + size, 0)

console.log(
  downloads
    .toSorted((a, b) => b.size - a.size)
    .map(({ fileName, size }) =>
      `  ${String(Math.round(size / 1024)).padStart(4)} KB  ${fileName}`
    )
    .join('\n'),
)
console.log(
  `\n${downloads.length} faces (of ${allFaces.length} offered), ${
    Math.round(totalBytes / 1024)
  } KB total -> ${FONTS_DIR}`,
)
console.log(`Wrote ${GENERATED_CSS}`)
